### ISSUE TITLE
this.internal is null error

### ISSUE THREAD

**Issue by FeehGamer** [LoneDev6/API-ItemsAdder#7]
Hello, I'm trying to use the Mana HUD from MagicCraft that was already there but I get this Error
```
[19:30:14] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Class v1.0b
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Core.d.a.d.q()" because "this.internal" is null
	at dev.lone.itemsadder.api.FontImages.PlayerHudWrapper.<init>(SourceFile:16) ~[ItemsAdder.jar:?]
	at dev.lone.itemsadder.api.FontImages.PlayerQuantityHudWrapper.<init>(SourceFile:12) ~[ItemsAdder.jar:?]
	at eu.mistland.classpl.events.PlayerEvents.onJoin(PlayerEvents.java:31) ~[Class-1.0b.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor250.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-381]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-381]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-381]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:360) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:302) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:307) ~[app:?]
	at net.minecraft.network.Connection.tick(Connection.java:555) ~[app:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[app:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1656) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-381]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

My code:
```
        BukkitScheduler scheduler = Bukkit.getServer().getScheduler();
        PlayerHudsHolderWrapper huds = new PlayerHudsHolderWrapper(player);
        PlayerQuantityHudWrapper manaHud =
                new PlayerQuantityHudWrapper(huds, "magiccraft:mana_bar");

        scheduler.scheduleSyncRepeatingTask(plugin, new Runnable() {
            @Override
            public void run() {
                float manaForManaHud = (float) ((ManaSystem.getCurrentPlayerMana(player) * 2) / 100);
                System.out.println(manaForManaHud);
                if(ManaSystem.getCurrentPlayerMana(player) < ManaSystem.getPlayerMana(player)){
                    ManaSystem.restoreMana(player, 5);
                    manaHud.setFloatValue(manaForManaHud);
                } else {
                    manaHud.setFloatValue(manaForManaHud);
                }
            }
        }, 0L, 2L * 20L);
```

**Comment by LoneDev6** [comment]
This should be already fixed.
Report here again if not: https://github.com/PluginBugs/Issues-ItemsAdder/issues
